### ISSUE TITLE
File can't be handled if rotated file can't be traced but new file is created

### ISSUE THREAD

**Issue by GilesChang** [bgreenlee/pygtail#34] opened 2017-04-17 09:06 UTC
The file can't be watched while the new file is created with same name, the size is smaller than the logged offset and the rotated file is not found. (Consider the rotate method is not copy truncate but change file)
The StopIteration exception will be raised and directly goes to _update_offset_file(). The offset is loaded from the offset file, but not the offset of the new log file.
Kindly suggest setting the offset to 0 directly and iterate the new log file.

**Comment by bobtiernay-okta** [comment] 2017-09-16 15:48
@GilesChang Can you please confirm if the referenced issue above is a duplicate? Thanks!

**Comment by GilesChang** [comment] 2017-09-18 06:58
Duplicate of #36

**Comment by JanMkl** [comment] 2018-06-29 10:07
The problem is that the offset that was read from the offset file is not set to zero in a case when the rotated log filename can't be identified. As the offset remains on the value that was the previous log file, the _filehandle() tries to seek the file to a offset that is non-existing. The problem can be solved by reseting the offset in case the _determine_rotated_logfile() returns None and the file size has been previously identified to be less than what the offset indicated. Below is a diff how I solved the problem.

-- core.py     2018-06-29 12:31:54.537744000 +0300
+++ core.py.org 2018-06-29 13:01:48.734196000 +0300
@@ -86,9 +86,6 @@
                 # might have been rotated.
                 # Look for the rotated file and process that if we find it.
                 self._rotated_logfile = self._determine_rotated_logfile()
-                # File was rotated but named in a way that couldn't be identified
-                if self._rotated_logfile == None:
-                    self._offset = 0
 
     def __del__(self):
         if self._filehandle():

**Comment by bgreenlee** [comment] 2022-10-30 19:07
Fixed with 2839302b426d5b0d320135876e4807fd6924e0b0

**Closed by bgreenlee** 2022-10-30 19:07 UTC
